### ISSUE TITLE
Suggested International Compatible UX + Mega Step Count Support

### ISSUE THREAD

**Issue by mdrideout** [lukepighetti/flutter_hotspot#2]
### Reasons 

- In order to provide internationalization by default, the controls can be changed to icons.
- In order to support a larger number of steps, the dots can be replaced with numbers, ex: (3 / 12)

### Suggestions

- [ ] End tour button is replaced with an "X" icon
- [ ] Next / Prev controls are forward / backward arrow icons
- [x] Dots are replaced with **[current step]/[total steps]**

**Comment by lukepighetti** [comment]
with >5 pages

<img width="479" alt="Screenshot 2024-06-25 at 5 57 50 PM" src="https://github.com/lukepighetti/flutter_hotspot/assets/666539/ea95d327-4124-4561-9443-3c1bc4031da1">

with <=5 pages

<img width="487" alt="Screenshot 2024-06-25 at 5 58 10 PM" src="https://github.com/lukepighetti/flutter_hotspot/assets/666539/c59117e6-d1cc-4a74-8505-bc64bbf33567">

**Comment by lukepighetti** [comment]
as a note, this can also be overridden by providing `HotspotProvider` with a custom `actionBuilder`

**Comment by lukepighetti** [comment]
going to leave these strings but they are overridable now by providing `HotspotProvider` with eg `actionBuilder: HotspotActionBuilder(doneText: "Fin!")`. And as always you can provide your own `actionBuilder`.

As a note, I did like the icon idea, but material doesn't really have a strong concept of a raised icon button that I'm aware of and I wasn't confident using regular `IconButton` in this context
